### ISSUE TITLE
The service memefs has failed to start

### ISSUE THREAD

**Issue by yosg** [Ceiridge/WinFsp-MemFs-Extended#13]
I got this error when I running the latest version of memefs:

``` bash
$ ./memefs-x64.exe -F NTFS -u "" -m X:
cannot create MEMFS
The service memefs has failed to start (Status=ffffffff).
```

**Comment by Ceiridge** [comment]
Can you find an error entry in the event viewer (eventvwr) under the _Application_ category regarding this?

**Comment by Ceiridge** [comment]
Also, do you
- have WinFsp installed
- use a 64 bit operating system
- use the memefs installer to install it

**Comment by yamosin** [comment]
> * have WinFsp installed
> * use a 64 bit operating system
> * use the memefs installer to install it

Have the same problem and already done this all,but seem like it because winfsp cant work but not this Extended plugin dont work

**Comment by Cologler** [comment]
Does not work after upgrade WinFsp to https://github.com/winfsp/winfsp/releases/tag/v2.0

**Comment by Ceiridge** [comment]
The installer installed an outdated winfsp dll. It is now fixed with the new installer.
First, uninstall the old memefs version, then install the new one.
