### ISSUE TITLE
wrong launchctl classname parameter on Readme-Installation.txt 

### ISSUE THREAD

**Issue by jht3QAQ** [Ceiridge/WinFsp-MemFs-Extended#15]
the launchctl parameter on [Readme-Installation.txt](https://github.com/Ceiridge/WinFsp-MemFs-Extended/blob/master/Readme-Installation.txt#L11) is `start memefs64 ramdisk "" \\.\R:`

but the classname on [InstallerScript.nsi](https://github.com/Ceiridge/WinFsp-MemFs-Extended/blob/master/InstallerScript.nsi#L5C9-L5C26) is `Memefs`

I think the parameter on Readme-Installation.txt should be changed to `start memefs ramdisk "" \\.\R:` to match it with InstallerScript.nsi

**Comment by Ceiridge** [comment]
You're right. I shouldn't have missed that.
