### ISSUE TITLE
sometimes when delete lot of small file, exe exit and memfs drive gone

### ISSUE THREAD

**Issue by linpinger** [Ceiridge/WinFsp-MemFs-Extended#4]
sometimes when delete lot of small file, exe exit and memfs drive gone

i try to repeat this error, but when use -d -1 -D D:\memefs.log
it print lots of log, log file size up to 300M

is there some arg for usefull log when it broken down ?

**Comment by Ceiridge** [comment]
Can you take a look into the Windows Event Viewer under the group _Applications_ and perhaps find an error message of memefs? Maybe you can find the .dmp minidump file that was probably generated.

How many files did you delete at once?
If you want to, you can zip the log file and it will have a much smaller size.

**Comment by linpinger** [comment]
错误应用程序名称: memefs-x64.exe，version: 0.0.0.0，timestamp: 0x62c3c313
erro module name: ntdll.dll，version: 6.1.7601.25920，timestamp: 0x6232acc3
exception code: 0xc0000005
error offset: 0x000000000002d52c
error process ID: 0x94c
错误应用程序start time: 0x01d8d39a5922d160
error exe path: C:\bin\WinFsp\bin\memefs-x64.exe
error module path: C:\Windows\SYSTEM32\ntdll.dll
report ID: c69ba260-3f99-11ed-b265-e0d55edda231

os: win7 x64 

and did not find any .dmp in C:\

**Comment by Ceiridge** [comment]
You may find the dump file in one of these folders:
```
C:\Windows\System32\config\systemprofile\AppData\Local\CrashDumps
%userprofile%\AppData\Local\CrashDumps
C:\Windows\ServiceProfiles\LocalService\AppData\Local\CrashDumps
```

Make sure to navigate to some of the paths with administrator rights, for example with a command prompt window started with admin rights.

Also please make sure to answer my other questions above.

**Comment by linpinger** [comment]
just now it broke again, there are only one folder with 3 files
plus i use total commander to manager files , not explorer
this time in event viewer, first is an error, then after a info
launcher-x64: terminated memefs64\ramdisk

**Comment by Ceiridge** [comment]
Please try to find the dump file and maybe zip the log to upload it.

If you want to, you can also try getting it to crash using the Windows Explorer to find out whether it only crashes because of Total Commander. In that case, it would probably be a concurrency race condition bug that would need to be fixed.

**Comment by linpinger** [comment]
ok, i find another problem
i use sandboxie run some temp program, i always put it in ramdisk created by imdisk, and it works fine
just now i run it in memfs, that program broken, so i terminated the memfs and create use imdisk, this time it works
so maybe i will not use memfs as pri option, though memefs is really good, like /dev/shm in linux

**Comment by Ceiridge** [comment]
I use memefs a lot and while not developing on it, it has not crashed for me. There is a known bug that programs, which read or write on the same file or maybe generally on memefs at the same, might cause strange file errors.
I have had only rare instances in which memefs had behaved differently from the normal NTFS filesystem driver.

Maybe you using Windows 7 causes some issues? At the moment, I think that Total Commander deletes files concurrently and this might cause a crash.
If you find the dumps, I can take a look at it later, or I will try to reproduce it myself.

**Comment by linpinger** [comment]
Thanks for your help, i do not find out any dumps in C:\
